# client_and_studio/scripts/core/chat_filter.gd
class_name ChatFilter
extends RefCounted

## Automated Chat & Text Content Filter using LDNOOBW Bad Words List

static var BAD_WORDS: PackedStringArray = PackedStringArray([
    "rosy palm and her 5 sisters",
    "blonde on blonde action",
    "leather straight jacket",
    "prince albert piercing",
    "missionary position",
    "alabama hot pocket",
    "double penetration",
    "chocolate rosebuds",
    "leather restraint",
    "cleveland steamer",
    "two girls one cup",
    "wrinkled starfish",
    "one cup two girls",
    "alaskan pipeline",
    "female squirting",
    "reverse cowgirl",
    "one guy one jar",
    "girls gone wild",
    "brunette action",
    "yellow showers",
    "carpet muncher",
    "menage a trois",
    "acrotomophilia",
    "mound of venus",
    "male squirting",
    "pleasure chest",
    "rusty trombone",
    "beaver cleaver",
    "blow your load",
    "golden shower",
    "piece of shit",
    "dirty sanchez",
    "dirty pillows",
    "shaved beaver",
    "carpetmuncher",
    "blonde action",
    "2 girls 1 cup",
    "brown showers",
    "dingleberries",
    "suicide girls",
    "splooge moose",
    "how to murder",
    "clover clamps",
    "motherfucker",
    "big knockers",
    "ball licking",
    "dendrophilia",
    "sultry women",
    "doggie style",
    "tainted love",
    "make me come",
    "fudge packer",
    "donkey punch",
    "masturbation",
    "vorarephilia",
    "wrapping men",
    "raging boner",
    "masturbating",
    "ball sucking",
    "ball kicking",
    "shaved pussy",
    "urethra play",
    "fuck buttons",
    "barely legal",
    "style doggy",
    "coprophilia",
    "big breasts",
    "beaver lips",
    "intercourse",
    "ejaculation",
    "pornography",
    "doggy style",
    "blue waffle",
    "foot fetish",
    "cunnilingus",
    "tight white",
    "coprolagnia",
    "snowballing",
    "beastiality",
    "baby batter",
    "nsfw images",
    "tea bagging",
    "deep throat",
    "nimphomania",
    "jelly donut",
    "girl on top",
    "dingleberry",
    "clusterfuck",
    "fudgepacker",
    "violet wand",
    "auto erotic",
    "doggiestyle",
    "white power",
    "tongue in a",
    "pole smoker",
    "double dong",
    "venus mound",
    "bullet vibe",
    "spread legs",
    "nymphomania",
    "how to kill",
    "lemon party",
    "thumbzilla",
    "baby juice",
    "eat my ass",
    "strip club",
    "bestiality",
    "booty call",
    "black cock",
    "dominatrix",
    "undressing",
    "domination",
    "circlejerk",
    "lovemaking",
    "scissoring",
    "giant cock",
    "deepthroat",
    "ball gravy",
    "muff diver",
    "poop chute",
    "masturbate",
    "paedophile",
    "doggystyle",
    "autoerotic",
    "homoerotic",
    "muffdiving",
    "buttcheeks",
    "fingerbang",
    "bung hole",
    "bastinado",
    "barenaked",
    "big black",
    "towelhead",
    "throating",
    "shitblimp",
    "pedophile",
    "zoophilia",
    "strappado",
    "fingering",
    "sexuality",
    "anilingus",
    "gang bang",
    "poopchute",
    "date rape",
    "urophilia",
    "threesome",
    "jiggerboo",
    "rosy palm",
    "octopussy",
    "group sex",
    "dp action",
    "camel toe",
    "wet dream",
    "shrimping",
    "phone sex",
    "voyeurweb",
    "tribadism",
    "hard core",
    "fucktards",
    "jail bait",
    "ball sack",
    "hot chick",
    "dog style",
    "blumpkin",
    "clitoris",
    "arsehole",
    "assmunch",
    "piss pig",
    "slanteye",
    "dry hump",
    "babeland",
    "frotting",
    "swastika",
    "sexually",
    "goregasm",
    "ponyplay",
    "goo girl",
    "futanari",
    "camwhore",
    "butthole",
    "jailbait",
    "blow job",
    "hot carl",
    "birdlock",
    "goodpoop",
    "cornhole",
    "mr hands",
    "huge fat",
    "jack off",
    "ball gag",
    "hardcore",
    "god damn",
    "cumshots",
    "fellatio",
    "creampie",
    "vibrator",
    "daterape",
    "hand job",
    "taste my",
    "bangbros",
    "santorum",
    "kinkster",
    "bunghole",
    "worldsex",
    "bareback",
    "bollocks",
    "genitals",
    "pedobear",
    "strap on",
    "bastardo",
    "gangbang",
    "jiggaboo",
    "jerk off",
    "tub girl",
    "sodomize",
    "bulldyke",
    "knobbing",
    "omorashi",
    "poontang",
    "big tits",
    "bullshit",
    "neonazi",
    "jigaboo",
    "pisspig",
    "livesex",
    "pissing",
    "asshole",
    "handjob",
    "pegging",
    "topless",
    "blowjob",
    "fisting",
    "bitches",
    "schlong",
    "rimming",
    "tubgirl",
    "bastard",
    "tied up",
    "shibari",
    "upskirt",
    "camslut",
    "cumming",
    "splooge",
    "footjob",
    "swinger",
    "apeshit",
    "beaners",
    "gay sex",
    "shemale",
    "strapon",
    "girl on",
    "bondage",
    "playboy",
    "titties",
    "figging",
    "bangbus",
    "nig nog",
    "kinbaku",
    "dolcett",
    "raghead",
    "camgirl",
    "fucking",
    "wetback",
    "bukkake",
    "erotism",
    "humping",
    "nawashi",
    "panties",
    "cumshot",
    "nipples",
    "spastic",
    "twinkie",
    "viagra",
    "eunuch",
    "shitty",
    "tranny",
    "hooker",
    "rapist",
    "orgasm",
    "hentai",
    "erotic",
    "tosser",
    "goatse",
    "nutten",
    "sadism",
    "voyuer",
    "honkey",
    "snatch",
    "sexual",
    "beaner",
    "punany",
    "femdom",
    "spooge",
    "nipple",
    "rimjob",
    "dommes",
    "rectum",
    "g-spot",
    "sodomy",
    "gokkun",
    "feltch",
    "nigger",
    "escort",
    "nympho",
    "darkie",
    "nudity",
    "fuckin",
    "goatcx",
    "lolita",
    "vagina",
    "cialis",
    "nambla",
    "raping",
    "voyeur",
    "bimbos",
    "sexcam",
    "faggot",
    "incest",
    "juggs",
    "bitch",
    "vulva",
    "shota",
    "cocks",
    "negro",
    "panty",
    "penis",
    "dildo",
    "horny",
    "yiffy",
    "pikey",
    "boobs",
    "pubes",
    "busty",
    "spunk",
    "skeet",
    "fecal",
    "sucks",
    "semen",
    "nigga",
    "boner",
    "felch",
    "ecchi",
    "porno",
    "pussy",
    "queaf",
    "titty",
    "whore",
    "tushy",
    "queef",
    "kinky",
    "twink",
    "grope",
    "coons",
    "scat",
    "cunt",
    "tits",
    "mong",
    "cock",
    "coon",
    "spic",
    "orgy",
    "rape",
    "dick",
    "butt",
    "twat",
    "wank",
    "boob",
    "yaoi",
    "poof",
    "jizz",
    "anus",
    "poon",
    "milf",
    "shit",
    "2g1c",
    "sexo",
    "slut",
    "quim",
    "fuck",
    "nsfw",
    "suck",
    "nude",
    "paki",
    "pthc",
    "anal",
    "smut",
    "bdsm",
    "clit",
    "kike",
    "dvda",
    "guro",
    "sexy",
    "porn",
    "bbw",
    "fag",
    "tit",
    "s&m",
    "sex",
    "ass",
    "xxx",
    "cum",
    "xx",
    "🖕",
])

static func filter_text(input_text: String) -> String:
    var text := input_text
    var lower_text := text.to_lower()
    
    for word in BAD_WORDS:
        if word.is_empty():
            continue
        var pos := lower_text.find(word)
        while pos != -1:
            var asterisks := "*".repeat(word.length())
            text = text.substr(0, pos) + asterisks + text.substr(pos + word.length())
            lower_text = lower_text.substr(0, pos) + asterisks + lower_text.substr(pos + word.length())
            pos = lower_text.find(word, pos + word.length())
            
    return text
